services:
    laravel-app:
        build:
            context: docker/php
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini   # Configuração customizada do PHP
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # Arquivo de configuração do Xdebug
        ports:
            - "5173:5173"      # Vite (Frontend hot module replacement)
            - "6001:6001"      # Porta para WebSockets com Laravel Echo
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - XDEBUG_MODE=debug
            - XDEBUG_CONFIG='client_host=host.docker.internal idekey=docker'
            - PHP_IDE_CONFIG=serverName=docker
            - SOCKET_PORT=6001 # Definir porta do WebSocket
        depends_on:
            - redis
            - mysql
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"              # Porta para acessar o NGINX (HTTP)
        volumes:
            - .:/var/www/html:ro     # Monta os arquivos da aplicação no contêiner para o NGINX
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # Configuração NGINX
        depends_on:
            - laravel-app            # Start apenas após o serviço `laravel-app`
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"            # Porta padrão do Redis
        volumes:
            - redis-data:/data
        networks:
            - app-network

    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - "3306:3306"            # Banco MySQL
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ROOT_PASSWORD: app
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

volumes:
    redis-data:
    mysql-data:

networks:
    app-network:
        driver: bridge
